# Generated by Django 2.2 on 2020-10-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('genere', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
